/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaVendas.view;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemaVendas.model.dao.ClienteDAO;
import sistemaVendas.model.dao.ProdutoDAO;

/**
 *
 * @author carva
 */
public class LancamentoNota extends javax.swing.JFrame {

    /**
     * Creates new form LancamentoNota
     */
    public LancamentoNota() {
        initComponents();
        carregarProdutos();
        carregarClientes();
        inicializarTabela();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_LimparCampos = new javax.swing.JButton();
        btn_Cadastrar = new javax.swing.JButton();
        btn_Listar = new javax.swing.JButton();
        btn_Voltar = new javax.swing.JButton();
        lbl_CadastroCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Clientes = new javax.swing.JTable();
        jLabel = new javax.swing.JLabel();
        txt_IdNota = new javax.swing.JTextField();
        lbl_Endereco = new javax.swing.JLabel();
        txt_DataVenda = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_Quantidade = new javax.swing.JTextField();
        btn_Adicionar = new javax.swing.JButton();
        cmb_Cliente = new javax.swing.JComboBox<>();
        cmb_Produto = new javax.swing.JComboBox<>();
        btn_LimparTabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Produto:");

        jLabel2.setText("Cliente:");

        btn_LimparCampos.setText("Limpar campos");
        btn_LimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparCamposActionPerformed(evt);
            }
        });

        btn_Cadastrar.setText("Cadastrar");
        btn_Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CadastrarActionPerformed(evt);
            }
        });

        btn_Listar.setText("Listar cadastrados");
        btn_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ListarActionPerformed(evt);
            }
        });

        btn_Voltar.setText("Voltar");
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        lbl_CadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_CadastroCliente.setText("Lançamento de Nota de Saída");

        tbl_Clientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Valor Unitário", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_Clientes);

        jLabel.setText("Código da Nota:");

        txt_IdNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_IdNotaActionPerformed(evt);
            }
        });

        lbl_Endereco.setText("Data da venda:");

        txt_DataVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_DataVendaActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade:");

        txt_Quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_QuantidadeActionPerformed(evt);
            }
        });

        btn_Adicionar.setText("Adicionar");
        btn_Adicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AdicionarActionPerformed(evt);
            }
        });

        cmb_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum cliente selecionado" }));
        cmb_Cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ClienteActionPerformed(evt);
            }
        });

        cmb_Produto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum cliente selecionado" }));
        cmb_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_ProdutoActionPerformed(evt);
            }
        });

        btn_LimparTabela.setText("Limpar Tabela");
        btn_LimparTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LimparTabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(btn_Voltar)
                .addGap(60, 60, 60)
                .addComponent(lbl_CadastroCliente)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_Endereco)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_LimparCampos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(btn_Adicionar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cmb_Produto, 0, 223, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txt_IdNota, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_DataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cmb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(jScrollPane1)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Listar)
                        .addGap(33, 33, 33)
                        .addComponent(btn_LimparTabela)
                        .addGap(34, 34, 34)
                        .addComponent(btn_Cadastrar)
                        .addGap(64, 64, 64)))
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CadastroCliente)
                    .addComponent(btn_Voltar))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(txt_IdNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmb_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Endereco)
                    .addComponent(txt_DataVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cmb_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LimparCampos)
                    .addComponent(btn_Adicionar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_LimparTabela)
                    .addComponent(btn_Cadastrar)
                    .addComponent(btn_Listar))
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel tableModel;
    
    private void inicializarTabela() {
        
        tableModel = new DefaultTableModel(
            new Object[][]{},
            new String[]{"Produto", "Quantidade", "Valor Unitário", "Total"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tbl_Clientes.setModel(tableModel);
    }
    
    private void btn_LimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btn_LimparCamposActionPerformed

    private void btn_CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CadastrarActionPerformed

    }//GEN-LAST:event_btn_CadastrarActionPerformed

    private void btn_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ListarActionPerformed

    }//GEN-LAST:event_btn_ListarActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        Menu telaMenu = new Menu();
        telaMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    private void txt_IdNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_IdNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_IdNotaActionPerformed

    private void txt_DataVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_DataVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_DataVendaActionPerformed

    private void txt_QuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_QuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_QuantidadeActionPerformed

    private void limparCampos(){
        cmb_Produto.setSelectedIndex(-1);
        cmb_Cliente.setSelectedIndex(-1);
        txt_Quantidade.setText("");
        txt_IdNota.setText("");
        txt_DataVenda.setText("");
        txt_Quantidade.requestFocus();
    }

    private void btn_AdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AdicionarActionPerformed
        try {
            if (txt_IdNota.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe o código da nota!", "Aviso",
                JOptionPane.WARNING_MESSAGE);
            txt_IdNota.requestFocus();
            return;
            }

            if (cmb_Cliente.getSelectedIndex() == -1 ||
            cmb_Cliente.getSelectedItem().toString().trim().isEmpty() ||
            cmb_Cliente.getSelectedItem().toString().equals("Nenhum cliente selecionado")) {
            JOptionPane.showMessageDialog(this, "Selecione um cliente!", "Aviso",
                JOptionPane.WARNING_MESSAGE);
            cmb_Cliente.requestFocus();
            return;
            }

            if (txt_DataVenda.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Informe a data da venda!", "Aviso",
                JOptionPane.WARNING_MESSAGE);
            txt_DataVenda.requestFocus();
            return;
            }

            if (cmb_Produto.getSelectedIndex() == -1 || 
                cmb_Produto.getSelectedItem().toString().isEmpty() ||
                cmb_Produto.getSelectedItem().toString().equals("Selecione um produto")) {
                JOptionPane.showMessageDialog(this, "Selecione um produto!", "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            if (txt_Quantidade.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Informe a quantidade!", "Aviso", 
                    JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String produtoSelecionado = cmb_Produto.getSelectedItem().toString();
            double quantidade;
            
            try {
                String quantidadeTexto = txt_Quantidade.getText().trim().replace(",", ".");

                try {
                    quantidade = Double.parseDouble(quantidadeTexto);
                    if (quantidade <= 0) {
                        JOptionPane.showMessageDialog(this, "Quantidade deve ser maior que zero!",
                            "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Quantidade deve ser um número válido!",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Quantidade deve ser um número válido!", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            ProdutoDAO produtoDAO = new ProdutoDAO();
            double valorUnitario = produtoDAO.getPrecoProdutoPorNome(produtoSelecionado);
            
            if (valorUnitario == 0.0) {
                JOptionPane.showMessageDialog(this, "Erro ao obter preço do produto!", 
                    "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            double total = quantidade * valorUnitario;
            
            String valorUnitarioFormatado = String.format("R$ %.2f", valorUnitario);
            String totalFormatado = String.format("R$ %.2f", total);
            
            tableModel.addRow(new Object[]{
                produtoSelecionado,
                quantidade,
                valorUnitarioFormatado,
                totalFormatado
            });
            
            limparCampos();
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + ex.getMessage(), 
                "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_AdicionarActionPerformed

    
    private void carregarProdutos() {
        try {
            ProdutoDAO produtoDAO = new ProdutoDAO();
            cmb_Produto.removeAllItems();

            List<String> nomesProdutos = produtoDAO.getNomesProdutos();

            for (String nome : nomesProdutos) {
                cmb_Produto.addItem(nome);
            }
            
            cmb_Produto.setSelectedIndex(-1);

        } catch (Exception ex) {
            System.out.println("Erro ao carregar produtos: " + ex.getMessage());
            cmb_Produto.addItem("Erro ao carregar produtos");
        }
    }
    
    private void cmb_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ProdutoActionPerformed

    private void carregarClientes() {
        try {
            ClienteDAO clienteDAO = new ClienteDAO();
            cmb_Cliente.removeAllItems();
            

            List<String> nomesClientes = clienteDAO.getNomesClientes();

            for (String nome : nomesClientes) {
                cmb_Cliente.addItem(nome);
            }

            cmb_Cliente.setSelectedIndex(-1);

        } catch (Exception ex) {
            System.out.println("Erro ao carregar clientes: " + ex.getMessage());
            cmb_Cliente.addItem("Erro ao carregar clientes");
        }
    }
    
    private void cmb_ClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_ClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_ClienteActionPerformed

    private void btn_LimparTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparTabelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LimparTabelaActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LancamentoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LancamentoNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Adicionar;
    private javax.swing.JButton btn_Cadastrar;
    private javax.swing.JButton btn_LimparCampos;
    private javax.swing.JButton btn_LimparTabela;
    private javax.swing.JButton btn_Listar;
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JComboBox<String> cmb_Cliente;
    private javax.swing.JComboBox<String> cmb_Produto;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_CadastroCliente;
    private javax.swing.JLabel lbl_Endereco;
    private javax.swing.JTable tbl_Clientes;
    private javax.swing.JTextField txt_DataVenda;
    private javax.swing.JTextField txt_IdNota;
    private javax.swing.JTextField txt_Quantidade;
    // End of variables declaration//GEN-END:variables
}
