/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaVendas.view;

import java.util.List;
import sistemaVendas.model.Nota;
import sistemaVendas.model.dao.NotaDAO;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pichau
 */
public class ListaNotasCadastradas extends javax.swing.JFrame {

    /**
     * Creates new form ListaNotasCadastradas
     */
    public ListaNotasCadastradas() {
        initComponents();
        tableModel = (DefaultTableModel) tbl_NotasCadastradas.getModel(); 
        carregarTabelaNotas();
    }
    
    private DefaultTableModel tableModel;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_CadastroCliente = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_NotasCadastradas = new javax.swing.JTable();
        btn_Voltar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_CadastroCliente.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbl_CadastroCliente.setText("Notas de Saída Cadastradas");

        tbl_NotasCadastradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código da Nota", "Cliente", "Data Venda", "Total"
            }
        ));
        jScrollPane1.setViewportView(tbl_NotasCadastradas);

        btn_Voltar1.setText("Voltar");
        btn_Voltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Voltar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(btn_Voltar1)
                        .addGap(43, 43, 43)
                        .addComponent(lbl_CadastroCliente)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_CadastroCliente)
                    .addComponent(btn_Voltar1))
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Voltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Voltar1ActionPerformed
        LancamentoNota telaNota = new LancamentoNota();
        telaNota.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_Voltar1ActionPerformed
    
    private void carregarTabelaNotas() {
        tableModel.setRowCount(0);

        NotaDAO notaDAO = new NotaDAO();
        List<Nota> notas = notaDAO.listarNotasComCliente();

        for (Nota nota : notas) {
            tableModel.addRow(new Object[]{
                nota.getId(),
                nota.getClienteNome(),
                nota.getDataVenda(),
                nota.getValorTotal()
            });
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaNotasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaNotasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaNotasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaNotasCadastradas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaNotasCadastradas().setVisible(true);
            }
        });       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Voltar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_CadastroCliente;
    private javax.swing.JTable tbl_NotasCadastradas;
    // End of variables declaration//GEN-END:variables
}
